/**
 * blog-topics.mjs
 *
 * Geprioriteerde lijst van blog-onderwerpen voor vpnr.nl.
 * Geordend op: zoekvolume × affiliate-potentieel × ontbrekende dekking.
 *
 * Het generate-blog-post.mjs script pakt automatisch het eerste onderwerp
 * waarvan de slug nog niet in posts.ts bestaat.
 * Voeg nieuwe onderwerpen onderaan toe — ze komen vanzelf aan de beurt.
 */

export const BLOG_TOPICS = [

  // ─── HOGE PRIORITEIT: veel volume + directe conversie ──────────────────────
  {
    keyword: 'vpn china',
    slug: 'vpn-china-gebruiken',
    title: 'VPN gebruiken in China (2026): welke werken nog?',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'purevpn'],
    context: 'China blokkeert bijna alle VPNs via de Great Firewall. Bespreek welke VPNs obfuscatie bieden (NordVPN Obfuscated Servers, Surfshark Camouflage). Juridisch kader voor toeristen: gebruik is gedoogd. Praktische tips: installeer voor vertrek, test server-locaties.',
  },
  {
    keyword: 'expressvpn review',
    slug: 'expressvpn-review',
    title: 'ExpressVPN review 2026: snelste VPN, maar ook de duurste?',
    category: 'Review',
    relatedProviders: ['expressvpn', 'nordvpn', 'surfshark'],
    context: 'Eerlijke, uitgebreide review. ExpressVPN is premium geprijsd (~€8,32/mnd). Bespreek: Lightway protocol (eigen, snel), 105 landen, TrustedServer (RAM-only), Netflix/streaming-compatibiliteit. Vergelijk snelheid en prijs direct met NordVPN.',
  },
  {
    keyword: 'vpn smart tv instellen',
    slug: 'vpn-smart-tv-instellen',
    title: 'VPN instellen op Smart TV (2026): Samsung, LG en Android TV',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'cyberghost'],
    context: 'Drie methoden: (1) directe app op Android TV via Play Store, (2) SmartDNS voor Samsung Tizen en LG webOS, (3) router-methode als universele fallback. Welke VPNs een tvOS/AndroidTV-app hebben.',
  },
  {
    keyword: 'gratis vpn gevaren',
    slug: 'gratis-vpn-gevaren',
    title: 'De gevaren van gratis VPN: waarom je beter betaalt (2026)',
    category: 'Uitleg',
    relatedProviders: ['protonvpn', 'hideme', 'nordvpn'],
    context: 'Concrete gevaren: datalogging + verkoop aan derden, malware (Hola VPN casus), bandbreedtebeperking, DNS-lekken, zwakke encryptie. Benoem dat ProtonVPN WEL een betrouwbaar gratis plan heeft (geen tijdslimiet, geen logs).',
  },
  {
    keyword: 'vpn openbaar wifi beveiliging',
    slug: 'vpn-openbaar-wifi',
    title: 'VPN op openbaar wifi: waarom het essentieel is in 2026',
    category: 'Uitleg',
    relatedProviders: ['nordvpn', 'surfshark', 'protonvpn'],
    context: 'Uitleg van man-in-the-middle aanvallen, evil twin hotspots, packet sniffing. Verschil HTTPS vs volledige VPN-encryptie. Praktische tips voor café, hotel, luchthaven. NordVPN auto-connect op openbare netwerken.',
  },
  {
    keyword: 'vpn firestick instellen',
    slug: 'vpn-firestick-instellen',
    title: 'VPN instellen op Amazon Firestick (2026): stap voor stap',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'cyberghost'],
    context: 'Fire TV Stick heeft een Android-gebaseerd OS. Methode 1: directe app via Amazon Appstore (NordVPN, Surfshark, CyberGhost staan er allemaal in). Methode 2: sideloading via ADB. Welke werkt het beste voor Netflix US.',
  },
  {
    keyword: 'nordvpn review',
    slug: 'nordvpn-review-2026',
    title: 'NordVPN review 2026: nog steeds de beste keuze?',
    category: 'Review',
    relatedProviders: ['nordvpn', 'surfshark', 'expressvpn'],
    context: 'Uitgebreide NordVPN review. Behandel: NordLynx (WireGuard-gebaseerd) snelheidstests op Nederlandse servers, Threat Protection, Meshnet, dubbele VPN, 6400+ servers. Audits door Deloitte. Prijs-kwaliteit vs Surfshark.',
  },
  {
    keyword: 'surfshark review',
    slug: 'surfshark-review-2026',
    title: 'Surfshark review 2026: het beste betaalbare VPN?',
    category: 'Review',
    relatedProviders: ['surfshark', 'nordvpn', 'cyberghost'],
    context: 'Surfshark review. USP: onbeperkte apparaten. Behandel: CleanWeb (adblocker), Camouflage mode, MultiHop, snelheidstests. Zwaktes: kleinere serverfleet dan NordVPN. Prijs: laagste bij 2-jaar deal.',
  },
  {
    keyword: 'vpn split tunneling',
    slug: 'vpn-split-tunneling',
    title: 'VPN split tunneling uitgelegd: wat is het en wanneer gebruik je het?',
    category: 'Uitleg',
    relatedProviders: ['nordvpn', 'surfshark', 'protonvpn'],
    context: 'Leg uit: bij split tunneling loopt alleen geselecteerd verkeer via VPN. Use cases: Netflix via VPN + thuisbank via lokaal IP. Inverse split tunneling. Welke VPNs dit goed implementeren (NordVPN, Surfshark). Niet beschikbaar op iOS.',
  },
  {
    keyword: 'dns lek vpn',
    slug: 'vpn-dns-lek-test',
    title: 'DNS-lek bij VPN: hoe test je het en hoe los je het op? (2026)',
    category: 'Uitleg',
    relatedProviders: ['nordvpn', 'protonvpn', 'hideme'],
    context: 'Wat is een DNS-lek: jouw ISP ziet welke sites je bezoekt ondanks VPN. Test-tools: ipleak.net, dnsleaktest.com. Oorzaken: Windows Smart Multi-Homed DNS. Fix: DNS over HTTPS inschakelen + VPN met eigen DNS-servers. IPv6-lekken ook bespreken.',
  },

  // ─── MEDIUM PRIORITEIT: gezond volume + goede conversiepotentie ────────────
  {
    keyword: 'nordvpn vs protonvpn',
    slug: 'nordvpn-vs-protonvpn',
    title: 'NordVPN vs ProtonVPN (2026): snelheid versus privacy',
    category: 'Vergelijking',
    relatedProviders: ['nordvpn', 'protonvpn'],
    context: 'Head-to-head vergelijking. NordVPN: sneller, groter netwerk, meer features. ProtonVPN: Zwitsers recht, open source, Secure Core servers, sterkere privacygaranties. Vergelijk prijs, streaming-werking, gratis optie.',
  },
  {
    keyword: 'surfshark vs cyberghost',
    slug: 'surfshark-vs-cyberghost',
    title: 'Surfshark vs CyberGhost (2026): welke budget-VPN wint?',
    category: 'Vergelijking',
    relatedProviders: ['surfshark', 'cyberghost'],
    context: 'CyberGhost: 9000+ servers, 45-daagen garantie, gespecialiseerde streaming servers. Surfshark: onbeperkte apparaten, goedkoper bij 2-jaar. Vergelijk Netflix-compatibiliteit, snelheid, privacy (CyberGhost is Roemeens, eigenaar Kape).',
  },
  {
    keyword: 'vpn studenten',
    slug: 'beste-vpn-voor-studenten',
    title: 'Beste VPN voor studenten 2026: goedkoop, snel en veilig',
    category: 'Gids',
    relatedProviders: ['surfshark', 'nordvpn', 'protonvpn'],
    context: 'Studenten zoeken: goedkoop (Surfshark €1,99/mnd), werkt op uni-netwerk (sommige blokkeren VPN-poorten), Netflix US, veilig torrenten voor studiemateriaal, bescherming op openbaar wifi.',
  },
  {
    keyword: 'vpn playstation instellen',
    slug: 'vpn-op-playstation',
    title: 'VPN instellen op PS4 en PS5 (2026): zo doe je het',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'cyberghost'],
    context: 'PS4/PS5 heeft geen native VPN-app. Drie methoden: (1) via router, (2) PC als hotspot met gedeelde VPN-verbinding, (3) Mac internet sharing. Voordelen: geo-geblokkeerde games early release, DDoS-bescherming bij online gaming.',
  },
  {
    keyword: 'vpn apple tv instellen',
    slug: 'vpn-op-apple-tv',
    title: 'VPN instellen op Apple TV (2026): native app of SmartDNS',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'protonvpn'],
    context: 'Apple TV 4K (gen 3+) ondersteunt native VPN-apps via tvOS. NordVPN en ProtonVPN hebben een tvOS-app. Voor oudere modellen: SmartDNS of router-methode. Stap-voor-stap instructies.',
  },
  {
    keyword: 'protonvpn gratis plan',
    slug: 'protonvpn-gratis-plan',
    title: 'ProtonVPN gratis: de betrouwbaarste gratis VPN in 2026?',
    category: 'Review',
    relatedProviders: ['protonvpn', 'hideme', 'nordvpn'],
    context: 'ProtonVPN gratis: onbeperkte data (uniek!), 3 serverlanden (NL, VS, JP), geen logs, maar lagere snelheid (wachtrij bij piekuren). Vergelijk met Windscribe (15GB/mnd), hide.me (10GB/mnd). Is het goed genoeg voor dagelijks gebruik?',
  },
  {
    keyword: 'vpn obfuscatie',
    slug: 'vpn-obfuscatie-uitgelegd',
    title: 'VPN obfuscatie uitgelegd: verberg dat je VPN gebruikt (2026)',
    category: 'Uitleg',
    relatedProviders: ['nordvpn', 'surfshark', 'purevpn'],
    context: 'Obfuscatie (stealth VPN) vermijdt deep packet inspection (DPI). Protocollen: Shadowsocks, Obfs4, NordVPN Obfuscated Servers, Surfshark Camouflage. Nodig in China, Rusland, Iran, UAE. Nadeel: iets lagere snelheid.',
  },
  {
    keyword: 'surfshark korting 2026',
    slug: 'surfshark-korting-2026',
    title: 'Surfshark korting 2026: bespaar tot 87% op het beste budget-VPN',
    category: 'Deals',
    relatedProviders: ['surfshark', 'nordvpn'],
    context: 'Actuele Surfshark deal: 24-maanden abonnement voor ~€1,99/mnd (87% korting + 3 gratis maanden). Wanneer zijn de beste deals (Black Friday). Vergelijk met NordVPN-deal. Is Surfshark het waard voor die prijs?',
  },
  {
    keyword: 'netflix us kijken vpn',
    slug: 'netflix-us-kijken-vpn',
    title: 'Netflix US kijken met VPN in Nederland (2026): zo doe je het',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'cyberghost'],
    context: 'Stap-voor-stap: (1) kies juiste VPN, (2) verbind met VS-server, (3) open Netflix in incognitovenster. Foutmelding "proxy gedetecteerd": wisselen van server. Waarom Netflix blokkeert. Content-verschil NL vs US-catalogus.',
  },
  {
    keyword: 'vpn gaming ping',
    slug: 'vpn-gaming-minder-lag',
    title: 'VPN voor gaming: verlaag je ping en speel beschermd (2026)',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'cyberghost'],
    context: 'Wanneer VPN ping verlaagt (ISP throttling, betere route naar game-server) en wanneer niet (extra hops). DDoS-bescherming. Geo-unlock: vroegere release van games. WireGuard als snelste protocol voor gaming. Praktische test: Fortnite, CoD, Valorant.',
  },

  // ─── LAGERE PRIORITEIT: long-tail, aanvullende coverage ────────────────────
  {
    keyword: 'vpn chromebook',
    slug: 'vpn-op-chromebook',
    title: 'VPN instellen op Chromebook (2026): app, Linux of ingebouwd',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'protonvpn'],
    context: 'Drie methoden: (1) Android-app via Play Store, (2) Linux-container via CLI, (3) ingebouwde Chrome OS VPN (L2TP/IKEv2 handmatig). Welke methode het gemakkelijkst is.',
  },
  {
    keyword: 'vpn linux ubuntu',
    slug: 'vpn-op-linux-instellen',
    title: 'VPN instellen op Linux (2026): Ubuntu, Debian en Mint',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'protonvpn', 'surfshark'],
    context: 'NordVPN heeft een goede Linux CLI-client (apt install nordvpn). ProtonVPN ook. Behandel: NetworkManager GUI-methode, WireGuard handmatig instellen. Commando\'s voor Ubuntu/Debian stap voor stap.',
  },
  {
    keyword: 'vpn no logs',
    slug: 'vpn-no-logs-beleid',
    title: 'VPN no-logs beleid: wat betekent het echt? (2026)',
    category: 'Uitleg',
    relatedProviders: ['protonvpn', 'nordvpn', 'hideme'],
    context: 'Verschil: verbindingslogs (tijdstempel, duur) vs activiteitslogs (bezochte sites). Audits: NordVPN door Deloitte, ProtonVPN open source. Rechtszaken: NordVPN kon geen logs overhandigen omdat ze niet bestonden. RAM-only servers.',
  },
  {
    keyword: 'vpn bedrijven zakelijk',
    slug: 'vpn-voor-bedrijven',
    title: 'Beste VPN voor bedrijven en ZZP\'ers (2026)',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'protonvpn', 'surfshark'],
    context: 'Zakelijke VPN-behoeften: statisch IP, dedicated servers, teams-beheer, AVG-compliance. Behandel NordLayer (zakelijk NordVPN), Proton for Business, Surfshark Teams. Kosten per gebruiker vergelijken.',
  },
  {
    keyword: 'vpn double vpn',
    slug: 'double-vpn-uitgelegd',
    title: 'Double VPN uitgelegd: wanneer heb je dubbele beveiliging nodig?',
    category: 'Uitleg',
    relatedProviders: ['nordvpn', 'protonvpn'],
    context: 'Multi-hop / double VPN versleutelt twee keer via twee servers. Wanneer zinvol: journalisten, activisten, extreme privacybehoeften. Impact op snelheid (~40-60% trager). Welke VPNs: NordVPN (Dubbele VPN), ProtonVPN (Secure Core).',
  },
  {
    keyword: 'cyberghost review',
    slug: 'cyberghost-review-2026',
    title: 'CyberGhost review 2026: 9000+ servers, maar goed genoeg?',
    category: 'Review',
    relatedProviders: ['cyberghost', 'nordvpn', 'surfshark'],
    context: 'CyberGhost: grootste servernetwerk (9000+), 45-daagen geld-terug-garantie, gespecialiseerde streaming/torrenting-servers. Nadelen: eigenaar is Kape Technologies (controversieel), hogere prijs bij maandabonnement.',
  },
  {
    keyword: 'protonvpn review',
    slug: 'protonvpn-review-2026',
    title: 'ProtonVPN review 2026: de meest privacygerichte VPN?',
    category: 'Review',
    relatedProviders: ['protonvpn', 'nordvpn', 'hideme'],
    context: 'ProtonVPN: Zwitsers recht (strenge privacywetten), volledig open source code, Secure Core anti-surveillance servers, perfecte forward secrecy. Nadelen: duurder, minder servers dan NordVPN. Gratis plan uitlichten.',
  },
  {
    keyword: 'hide.me review',
    slug: 'hideme-review-2026',
    title: 'Hide.me review 2026: de beste VPN met Nederlandse roots?',
    category: 'Review',
    relatedProviders: ['hideme', 'nordvpn', 'protonvpn'],
    context: 'Hide.me is een Maleisische VPN maar heeft Nederlandse servers en richt zich op de NL-markt. Gratis plan (10GB/mnd). Sterke encryptie, 5 verbindingen. Nadelen: kleiner netwerk, langzamere ondersteuning. Beoordeling vanuit NL-perspectief.',
  },
  {
    keyword: 'vpn ipv6 lek',
    slug: 'vpn-ipv6-lek-voorkomen',
    title: 'IPv6-lek bij VPN: wat is het en hoe fix je het? (2026)',
    category: 'Uitleg',
    relatedProviders: ['nordvpn', 'protonvpn', 'surfshark'],
    context: 'IPv6 wordt niet altijd via VPN-tunnel gerouteerd, waardoor je echte IPv6-adres zichtbaar blijft. Test op ipleak.net. Fix: IPv6 uitschakelen in Windows/macOS, of kies VPN met native IPv6-ondersteuning (NordVPN, ProtonVPN).',
  },
  {
    keyword: 'vpn belgie streamz vtm',
    slug: 'vpn-belgie-streaming',
    title: 'VPN voor Belgische streaming (2026): VTM Go, Streamz en Play',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'cyberghost'],
    context: 'Belgische streamingdiensten zijn geo-gelocked. VTM Go en Streamz vereisen een Belgisch IP-adres. Welke VPN heeft Belgische servers die werken. Stap-voor-stap voor vanuit Nederland kijken naar Belgisch TV-aanbod.',
  },
  {
    keyword: 'vpn poort forwarding',
    slug: 'vpn-poort-forwarding',
    title: 'VPN poort-doorschakeling (port forwarding) uitgelegd (2026)',
    category: 'Uitleg',
    relatedProviders: ['protonvpn', 'purevpn', 'hideme'],
    context: 'Port forwarding via VPN voor torrenten (snellere downloads als seed), thuis-server bereikbaar via internet, gaming-servers hosten. Welke VPNs dit ondersteunen: ProtonVPN (ingebouwd), PureVPN, AirVPN. Waarom de meeste VPNs het NIET bieden (security).',
  },
  {
    keyword: 'expressvpn korting',
    slug: 'expressvpn-korting-2026',
    title: 'ExpressVPN korting 2026: bespaar op de snelste VPN',
    category: 'Deals',
    relatedProviders: ['expressvpn', 'nordvpn', 'surfshark'],
    context: 'ExpressVPN-deal: 12 maanden + 3 gratis = ~€6,39/mnd (49% korting). Is het de meerprijs waard t.o.v. NordVPN? Wanneer te kopen. Vergelijkingstabel met actuele prijzen van top-VPNs.',
  },
  {
    keyword: 'vpn senioren ouderen',
    slug: 'beste-vpn-voor-senioren',
    title: 'Beste VPN voor senioren (2026): eenvoudig, veilig en betaalbaar',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'cyberghost'],
    context: 'Criteria voor 60+: eenvoudige installatie (één klik verbinden), duidelijke app, goede klantenservice (telefoon/chat), geen technische kennis nodig. NordVPN beste keuze (simpelste app), CyberGhost als alternatief (45-daagen garantie).',
  },
  {
    keyword: 'vpn disney plus',
    slug: 'vpn-disney-plus',
    title: 'VPN voor Disney+ in 2026: werkt het nog en hoe?',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'cyberghost'],
    context: 'Disney+ blokkeert actief VPN-verkeer. Welke VPNs werken nog (NordVPN, Surfshark). Welke extra content beschikbaar is in de VS t.o.v. Nederland. Tips bij blokkade-foutmelding. Verschil met Netflix-blokkade.',
  },
  {
    keyword: 'vpn versus tor',
    slug: 'vpn-vs-tor-browser',
    title: 'VPN vs Tor: verschil, voor/nadelen en wanneer wat te kiezen (2026)',
    category: 'Uitleg',
    relatedProviders: ['protonvpn', 'nordvpn'],
    context: 'Vergelijking: VPN (snelheid, één vertrouwde partij) vs Tor (anonimiteit, traag, geen vertrouwde partij). Onion over VPN (NordVPN). VPN over Tor (ProtonVPN Secure Core). Wanneer wat kiezen: journalisten, activisten, dagelijks gebruik.',
  },
  {
    keyword: 'vpn kopen beginners',
    slug: 'vpn-kopen-gids',
    title: 'VPN kopen in 2026: complete beginnersgids',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark', 'protonvpn'],
    context: 'Stap-voor-stap voor beginners: (1) wat heb je nodig? (2) welke criteria zijn belangrijk? (3) top 3 aanbevelingen per budget. Behandel: protocol, no-logs, apparaatlimieten, geld-terug-garantie. Vermijd te technische taal.',
  },
  {
    keyword: 'vpn snelheid test nederland',
    slug: 'vpn-snelheid-vergelijken',
    title: 'VPN snelheidstest 2026: welke VPN is het snelst in Nederland?',
    category: 'Vergelijking',
    relatedProviders: ['nordvpn', 'surfshark', 'expressvpn'],
    context: 'Snelheidsvergelijking via Nederlandse servers met speedtest.net. Protocols: NordLynx (NordVPN), WireGuard (Surfshark), Lightway (ExpressVPN). Tabel: download, upload, ping. Welk protocol het snelste is per VPN.',
  },
  {
    keyword: 'vpn reisrouter',
    slug: 'vpn-op-reisrouter',
    title: 'VPN op een reisrouter: alle apparaten tegelijk beveiligd (2026)',
    category: 'Gids',
    relatedProviders: ['nordvpn', 'surfshark'],
    context: 'Reisrouters (GL.iNet Beryl AX, Slate AX) hebben ingebouwde VPN-ondersteuning. Voordelen: geen VPN-app nodig op elk apparaat, werkt ook op Smart TV en spelconsoles. Hoe instellen met NordVPN of Surfshark.',
  },
  {
    keyword: 'purevpn review',
    slug: 'purevpn-review-2026',
    title: 'PureVPN review 2026: betaalbaar alternatief of teleurstelling?',
    category: 'Review',
    relatedProviders: ['purevpn', 'nordvpn', 'surfshark'],
    context: 'PureVPN: 6500+ servers, betaalbaar (~€1,49/mnd bij 5-jaar), port forwarding add-on. Verleden: had logincident in 2017. Is het nu verbeterd? Onpartijdige beoordeling.',
  },
]
